// Training methods + unlock thresholds, per skill.
//
// Ported from the legacy tips.js / next-steps.js pair and re-verified against
// runescape.wiki in mid-2026. The legacy data was both stale and, in places,
// fabricated — "Banded iron" (Mining) and "Gnome bench" (Construction) are not
// real pages, Pack yak was listed at 67 instead of 96, and Sinkholes were
// described as weekly when they reset daily. Everything below is checked
// against a live wiki page that actually exists.
//
// Two things the legacy DB missed entirely and that this app exists to cover:
//   1. The 99-120 / 99-110 bands. RS3 raised the artisan and gathering caps to
//      110 and several support skills to 120, and there is a whole tier-100+
//      content wave (primal ore, eternal magic trees, starbloom, eternal bows)
//      that never appears in the old file.
//   2. Realistic gp/hr on the methods where the money matters more than the XP.
//
// XP rates are per-hour at the low end of the method's band with no bonus XP,
// no avatar and no skilling outfit, unless a note says otherwise. Where the
// wiki quotes a rate "at 99", it is noted rather than silently used as the
// headline number — a rate you cannot hit for another 20 levels is a lie.

export type Intensity = "afk" | "moderate" | "click-intensive";

export interface TrainingMethod {
  id: string;
  name: string;
  /** Lowest level the method is usable at. */
  minLevel: number;
  /** Level at which the method stops being the best use of the hour. Omitted
   *  when the method stays viable to the skill cap. */
  maxLevel?: number;
  xpPerHour: number;
  /** Only set where the method is a genuine earner. Absent means "roughly
   *  break-even or a loss" — silence here is information. */
  gpPerHour?: number;
  intensity: Intensity;
  members: boolean;
  /** runescape.wiki page title. */
  wiki: string;
  note?: string;
}

export interface SkillUnlock {
  skill: number;
  level: number;
  label: string;
  blurb: string;
  wiki: string;
}

// ---------------------------------------------------------------------------
// Combat ladders
//
// Attack, Strength and Defence all draw from the same kills — RS3 lets you
// funnel all melee XP into one of them, so the rates below are "everything
// pointed at this skill", which is how players actually plan a grind.
// Constitution is different: it earns a fixed 1/3 of the style XP no matter
// which style you pick, so its ladder is the same content at a third the rate.
// ---------------------------------------------------------------------------

function meleeLadder(p: string): TrainingMethod[] {
  return [
    {
      id: `${p}-catacombs`,
      name: "Lumbridge Catacombs",
      minLevel: 1,
      maxLevel: 40,
      xpPerHour: 25000,
      intensity: "moderate",
      members: false,
      wiki: "Lumbridge Catacombs",
      note: "Dense, low-danger spawns right under a lodestone.",
    },
    {
      id: `${p}-slayer-tower`,
      name: "Slayer tasks (Slayer Tower)",
      minLevel: 40,
      maxLevel: 70,
      xpPerHour: 70000,
      intensity: "moderate",
      members: true,
      wiki: "Slayer Tower",
      note: "Slayer is the correct melee trainer from here — the combat XP is a by-product of a skill you also need.",
    },
    {
      id: `${p}-waterfiends`,
      name: "Waterfiends (Ancient Cavern)",
      minLevel: 60,
      maxLevel: 80,
      xpPerHour: 110000,
      intensity: "afk",
      members: true,
      wiki: "Waterfiend",
      note: "The classic long-AFK melee spot; drops crimson charms for Summoning.",
    },
    {
      id: `${p}-abyssal-demons`,
      name: "Abyssal demons",
      minLevel: 70,
      maxLevel: 90,
      xpPerHour: 160000,
      intensity: "moderate",
      members: true,
      wiki: "Abyssal demon",
      note: "85 Slayer for the task; killable off-task without it, at worse rates.",
    },
    {
      id: `${p}-ripper-demons`,
      name: "Ripper demons",
      minLevel: 90,
      maxLevel: 99,
      xpPerHour: 260000,
      intensity: "click-intensive",
      members: true,
      wiki: "Ripper Demon",
      note: "They burrow and reposition constantly — high APM, but the best pre-99 melee rate.",
    },
    {
      id: `${p}-arch-glacor`,
      name: "Arch-Glacor (normal mode)",
      minLevel: 99,
      xpPerHour: 400000,
      intensity: "moderate",
      members: true,
      wiki: "Arch-Glacor",
      note: "Conservative figure — the real rate scales hard with enrage and how many mechanics you leave enabled.",
    },
    {
      id: `${p}-sanctum`,
      name: "Sanctum of Rebirth",
      minLevel: 105,
      xpPerHour: 450000,
      gpPerHour: 8000000,
      intensity: "click-intensive",
      members: true,
      wiki: "Sanctum of Rebirth",
      note: "Rate assumes a competent group; solo is considerably slower.",
    },
  ];
}

function rangedLadder(p: string): TrainingMethod[] {
  return [
    {
      id: `${p}-catacombs`,
      name: "Lumbridge Catacombs",
      minLevel: 1,
      maxLevel: 40,
      xpPerHour: 22000,
      intensity: "moderate",
      members: false,
      wiki: "Lumbridge Catacombs",
    },
    {
      id: `${p}-slayer-tower`,
      name: "Slayer tasks with a bow",
      minLevel: 40,
      maxLevel: 70,
      xpPerHour: 65000,
      intensity: "moderate",
      members: true,
      wiki: "Slayer Tower",
    },
    {
      id: `${p}-glacors`,
      name: "Glacors",
      minLevel: 70,
      maxLevel: 90,
      xpPerHour: 150000,
      gpPerHour: 1500000,
      intensity: "moderate",
      members: true,
      wiki: "Glacor",
      note: "Ranged-friendly and drops the Glacor components used in Invention.",
    },
    {
      id: `${p}-airut`,
      name: "Airut",
      minLevel: 85,
      maxLevel: 99,
      xpPerHour: 230000,
      gpPerHour: 2000000,
      intensity: "moderate",
      members: true,
      wiki: "Airut",
      note: "Needs 'The Mighty Fall' for access; good XP with genuine drop value.",
    },
    {
      id: `${p}-arch-glacor`,
      name: "Arch-Glacor (normal mode)",
      minLevel: 99,
      xpPerHour: 400000,
      intensity: "moderate",
      members: true,
      wiki: "Arch-Glacor",
      note: "Conservative — scales with enrage and mechanic selection.",
    },
    {
      id: `${p}-shadow-reef`,
      name: "The Shadow Reef (ED3)",
      minLevel: 105,
      xpPerHour: 500000,
      gpPerHour: 6000000,
      intensity: "click-intensive",
      members: true,
      wiki: "The Shadow Reef",
      note: "Rate is for a practised solo run; a first-timer will not see this.",
    },
  ];
}

// ---------------------------------------------------------------------------
// TRAINING
// ---------------------------------------------------------------------------

export const TRAINING: Record<number, TrainingMethod[]> = {
  // --- 0 Attack -----------------------------------------------------------
  0: meleeLadder("atk"),

  // --- 1 Defence ----------------------------------------------------------
  1: meleeLadder("def"),

  // --- 2 Strength ---------------------------------------------------------
  2: meleeLadder("str"),

  // --- 3 Constitution -----------------------------------------------------
  // Same kills as the melee ladder. Constitution takes a fixed 1/3 of the
  // style XP, so it is never trained directly and never needs its own plan.
  3: [
    {
      id: "hp-passive-low",
      name: "Any combat (passive)",
      minLevel: 1,
      maxLevel: 70,
      xpPerHour: 25000,
      intensity: "moderate",
      members: false,
      wiki: "Constitution",
      note: "Constitution earns a third of whatever your style earns — there is no separate method.",
    },
    {
      id: "hp-passive-mid",
      name: "Slayer tasks (passive)",
      minLevel: 70,
      maxLevel: 99,
      xpPerHour: 80000,
      intensity: "moderate",
      members: true,
      wiki: "Slayer Tower",
    },
    {
      id: "hp-passive-high",
      name: "Boss rotations (passive)",
      minLevel: 99,
      xpPerHour: 140000,
      intensity: "click-intensive",
      members: true,
      wiki: "Arch-Glacor",
      note: "Constitution is usually the last combat skill to 120 purely because of the 1/3 rate.",
    },
  ],

  // --- 4 Ranged -----------------------------------------------------------
  4: rangedLadder("rng"),

  // --- 5 Prayer (cap 99) --------------------------------------------------
  5: [
    {
      id: "pra-ectofuntus",
      name: "Ectofuntus",
      minLevel: 1,
      maxLevel: 50,
      xpPerHour: 40000,
      intensity: "click-intensive",
      members: true,
      wiki: "Ectofuntus",
      note: "Quadruple XP per bone but heavy on running — only worth it if bones are your bottleneck, not time.",
    },
    {
      id: "pra-gilded-dragon",
      name: "Dragon bones at a gilded altar",
      minLevel: 1,
      maxLevel: 70,
      xpPerHour: 300000,
      intensity: "moderate",
      members: true,
      wiki: "Gilded altar",
      note: "Needs 75 Construction for the gilded altar, or use someone else's open house.",
    },
    {
      id: "pra-frost-bones",
      name: "Frost dragon bones at a gilded altar",
      minLevel: 1,
      maxLevel: 99,
      xpPerHour: 450000,
      intensity: "moderate",
      members: true,
      wiki: "Frost dragon bones",
      note: "No level gate — this is a cost ladder, not a level ladder.",
    },
    {
      id: "pra-searing-ashes",
      name: "Searing ashes + powder of burials",
      minLevel: 1,
      xpPerHour: 600000,
      intensity: "moderate",
      members: true,
      wiki: "Powder of burials",
      note: "Powder doubles ash XP and lets you scatter from the backpack — no altar trip. Conservative rate; a full auto-sanctifier setup goes higher.",
    },
    {
      id: "pra-infernal-ashes",
      name: "Infernal ashes (cheap filler)",
      minLevel: 1,
      xpPerHour: 250000,
      intensity: "afk",
      members: true,
      wiki: "Infernal ashes",
      note: "Much cheaper per XP than searing — the sensible default when you are not rich.",
    },
  ],

  // --- 6 Magic ------------------------------------------------------------
  6: [
    {
      id: "mag-catacombs",
      name: "Lumbridge Catacombs",
      minLevel: 1,
      maxLevel: 40,
      xpPerHour: 22000,
      intensity: "moderate",
      members: false,
      wiki: "Lumbridge Catacombs",
    },
    {
      id: "mag-slayer",
      name: "Slayer tasks with combat spells",
      minLevel: 40,
      maxLevel: 75,
      xpPerHour: 70000,
      intensity: "moderate",
      members: true,
      wiki: "Slayer Tower",
    },
    {
      id: "mag-nightmares",
      name: "Nightmare creatures",
      minLevel: 75,
      maxLevel: 90,
      xpPerHour: 170000,
      intensity: "afk",
      members: true,
      wiki: "Nightmare creature",
      note: "Long-AFK magic training; low attention, low reward.",
    },
    {
      id: "mag-kalgerion",
      name: "Kal'gerion demons",
      minLevel: 90,
      maxLevel: 99,
      xpPerHour: 250000,
      gpPerHour: 1200000,
      intensity: "moderate",
      members: true,
      wiki: "Kal'gerion demon",
      note: "Behind the Daemonheim resource dungeon — 90 Dungeoneering to get in.",
    },
    {
      id: "mag-arch-glacor",
      name: "Arch-Glacor (normal mode)",
      minLevel: 99,
      xpPerHour: 400000,
      intensity: "moderate",
      members: true,
      wiki: "Arch-Glacor",
    },
    {
      id: "mag-zuk",
      name: "Zamorakian Undercity",
      minLevel: 105,
      xpPerHour: 480000,
      gpPerHour: 7000000,
      intensity: "click-intensive",
      members: true,
      wiki: "Zamorakian Undercity",
      note: "Group content; rate assumes a full team that knows the rotation.",
    },
  ],

  // --- 7 Cooking (cap 99) -------------------------------------------------
  7: [
    {
      id: "cok-low-fish",
      name: "Whatever you can catch, on a fire",
      minLevel: 1,
      maxLevel: 62,
      xpPerHour: 130000,
      intensity: "moderate",
      members: false,
      wiki: "Cooking",
      note: "Cooking is fast and cheap — the only real question is what fish you can afford.",
    },
    {
      id: "cok-monkfish",
      name: "Monkfish",
      minLevel: 62,
      maxLevel: 80,
      xpPerHour: 280000,
      intensity: "moderate",
      members: true,
      wiki: "Monkfish",
      note: "With cooking gauntlets on a range the burn rate at 86 is under 0.5%.",
    },
    {
      id: "cok-sharks",
      name: "Sharks on a portable range",
      minLevel: 80,
      maxLevel: 94,
      xpPerHour: 350000,
      intensity: "moderate",
      members: true,
      wiki: "Shark",
      note: "Portable range gives a burn-rate reduction and sits next to a bank — the difference is worth the token cost.",
    },
    {
      id: "cok-cavefish",
      name: "Cavefish",
      minLevel: 94,
      xpPerHour: 380000,
      intensity: "moderate",
      members: true,
      wiki: "Cavefish",
      note: "Often cheaper per XP than sharks at this level depending on GE prices.",
    },
    {
      id: "cok-urns",
      name: "Cooking urns (passive top-up)",
      minLevel: 1,
      xpPerHour: 30000,
      intensity: "afk",
      members: true,
      wiki: "Portable range",
      note: "Not a method on its own — a ~10% bonus layered onto whatever you are already cooking.",
    },
  ],

  // --- 8 Woodcutting (cap 110) --------------------------------------------
  8: [
    {
      id: "wc-regular",
      name: "Regular and oak trees",
      minLevel: 1,
      maxLevel: 20,
      xpPerHour: 20000,
      intensity: "moderate",
      members: false,
      wiki: "Woodcutting",
    },
    {
      id: "wc-willow",
      name: "Willow trees",
      minLevel: 20,
      maxLevel: 35,
      xpPerHour: 35000,
      intensity: "moderate",
      members: false,
      wiki: "Willow logs",
    },
    {
      id: "wc-creeping-ivy",
      name: "Creeping ivy",
      minLevel: 35,
      maxLevel: 68,
      xpPerHour: 55000,
      intensity: "afk",
      members: true,
      wiki: "Creeping ivy",
      note: "Ivy vanishes instead of dropping logs — no banking, which is why it beats maples despite the lower per-cut XP.",
    },
    {
      id: "wc-choking-ivy",
      name: "Choking ivy",
      minLevel: 68,
      maxLevel: 94,
      xpPerHour: 95000,
      intensity: "afk",
      members: true,
      wiki: "Choking ivy",
      note: "The long AFK band. Rate climbs steadily across the 26 levels.",
    },
    {
      id: "wc-overgrown-idols",
      name: "Overgrown idols",
      minLevel: 81,
      maxLevel: 110,
      xpPerHour: 110000,
      intensity: "moderate",
      members: true,
      wiki: "Overgrown idol",
      note: "Anachronia; competitive with ivy and gives Big Game Hunter materials.",
    },
    {
      id: "wc-elder",
      name: "Elder trees",
      minLevel: 90,
      maxLevel: 110,
      xpPerHour: 130000,
      gpPerHour: 900000,
      intensity: "moderate",
      members: true,
      wiki: "Elder tree",
      note: "The best logs-for-profit tree; elder logs also feed Firemaking.",
    },
    {
      id: "wc-crystal",
      name: "Crystal trees",
      minLevel: 94,
      maxLevel: 100,
      xpPerHour: 150000,
      intensity: "moderate",
      members: true,
      wiki: "Crystal tree",
      note: "Prifddinas only — needs Plague's End. Boosted during the Ithell Voice of Seren.",
    },
    {
      id: "wc-golden-bamboo",
      name: "Golden bamboo",
      minLevel: 96,
      maxLevel: 110,
      xpPerHour: 140000,
      gpPerHour: 1200000,
      intensity: "moderate",
      members: true,
      wiki: "Golden bamboo",
      note: "Anachronia; the bamboo also bundles for Fletching XP at 96+.",
    },
    {
      id: "wc-eternal-magic",
      name: "Eternal magic trees",
      minLevel: 100,
      xpPerHour: 200000,
      intensity: "moderate",
      members: true,
      wiki: "Eternal magic tree",
      note: "The tier-100 wave. Rate is a conservative estimate — treat it as 'clearly the best', not as a precise figure.",
    },
  ],

  // --- 9 Fletching (cap 110) ----------------------------------------------
  9: [
    {
      id: "fle-shafts",
      name: "Headless arrows",
      minLevel: 1,
      maxLevel: 50,
      xpPerHour: 90000,
      intensity: "afk",
      members: false,
      wiki: "Headless arrow",
      note: "Attaching feathers is one click per batch — the cheapest AFK XP in the skill.",
    },
    {
      id: "fle-bows",
      name: "Maple through magic shieldbows",
      minLevel: 50,
      maxLevel: 81,
      xpPerHour: 150000,
      intensity: "moderate",
      members: true,
      wiki: "Magic shieldbow",
    },
    {
      id: "fle-darts",
      name: "Rune and dragon darts",
      minLevel: 81,
      maxLevel: 110,
      xpPerHour: 350000,
      intensity: "click-intensive",
      members: true,
      wiki: "Dragon dart",
      note: "Fastest Fletching XP in the game from 81 up, and it stays fastest — but you buy every point of it.",
    },
    {
      id: "fle-elder-bows",
      name: "Elder shieldbows",
      minLevel: 90,
      maxLevel: 100,
      xpPerHour: 200000,
      gpPerHour: 400000,
      intensity: "moderate",
      members: true,
      wiki: "Elder shieldbow",
      note: "The cheap alternative to darts — slower, but roughly break-even.",
    },
    {
      id: "fle-bamboo",
      name: "Bundling golden bamboo",
      minLevel: 96,
      maxLevel: 110,
      xpPerHour: 230000,
      intensity: "moderate",
      members: true,
      wiki: "Golden bamboo",
      note: "Pairs with cutting the bamboo yourself for a self-sufficient loop.",
    },
    {
      id: "fle-eternal",
      name: "Eternal magic bows and primal crossbows",
      minLevel: 100,
      xpPerHour: 300000,
      intensity: "moderate",
      members: true,
      wiki: "Eternal magic bow",
      note: "The 100-110 band. Rate conservative — the materials only became common recently.",
    },
  ],

  // --- 10 Fishing (cap 99) ------------------------------------------------
  10: [
    {
      id: "fsh-crayfish",
      name: "Crayfish",
      minLevel: 1,
      maxLevel: 20,
      xpPerHour: 11500,
      intensity: "moderate",
      members: false,
      wiki: "Fishing",
    },
    {
      id: "fsh-fly",
      name: "Fly fishing trout and salmon",
      minLevel: 20,
      maxLevel: 70,
      xpPerHour: 45000,
      intensity: "moderate",
      members: false,
      wiki: "Fishing",
      note: "Strong fishing urns push this to ~70k at 70.",
    },
    {
      id: "fsh-ghostly-sole",
      name: "Ghostly sole (City of Um)",
      minLevel: 66,
      xpPerHour: 60000,
      intensity: "afk",
      members: true,
      wiki: "Ghostly sole",
      note: "Requires the Necromancy! quest. The single longest-AFK method in the skill — lower XP, almost no attention.",
    },
    {
      id: "fsh-crystallise",
      name: "Fly fishing with Crystallise",
      minLevel: 70,
      maxLevel: 93,
      xpPerHour: 90000,
      intensity: "click-intensive",
      members: true,
      wiki: "Crystallise",
      note: "Up to ~118k/hr at 99. Needs Light Form and constant re-casting — this is the sweatiest option.",
    },
    {
      id: "fsh-menaphos",
      name: "Desert sole, catfish and beltfish (Menaphos)",
      minLevel: 72,
      maxLevel: 93,
      xpPerHour: 75000,
      gpPerHour: 500000,
      intensity: "moderate",
      members: true,
      wiki: "Raw desert sole",
      note: "Up to ~100k/hr at 99, and it banks real GP unlike fly fishing.",
    },
    {
      id: "fsh-croesus",
      name: "Colonised guards (Croesus Front)",
      minLevel: 88,
      xpPerHour: 95000,
      intensity: "moderate",
      members: true,
      wiki: "Croesus Front",
      note: "92 gets you every node. Not the fastest, but it feeds Croesus kills at the same time.",
    },
    {
      id: "fsh-waterfall",
      name: "Prifddinas waterfall fishing",
      minLevel: 94,
      xpPerHour: 200000,
      intensity: "click-intensive",
      members: true,
      wiki: "Prifddinas Waterfall Fishing",
      note: "Over 285k/hr at 99 — comfortably the fastest Fishing in the game, and the reason 94 is the real Fishing milestone.",
    },
    {
      id: "fsh-wobbegong",
      name: "Wobbegongs",
      minLevel: 96,
      xpPerHour: 120000,
      gpPerHour: 800000,
      intensity: "moderate",
      members: true,
      wiki: "Wobbegong",
      note: "Up to ~137k/hr at 99. Slower than the waterfall but far less demanding.",
    },
  ],

  // --- 11 Firemaking (cap 110) --------------------------------------------
  11: [
    {
      id: "fm-willow",
      name: "Willow logs on a bonfire",
      minLevel: 30,
      maxLevel: 45,
      xpPerHour: 60000,
      intensity: "afk",
      members: false,
      wiki: "Bonfire",
      note: "Always burn on a bonfire, never one log at a time — the bonfire bonus is not optional.",
    },
    {
      id: "fm-maple",
      name: "Maple logs on a bonfire",
      minLevel: 45,
      maxLevel: 60,
      xpPerHour: 110000,
      intensity: "afk",
      members: true,
      wiki: "Maple logs",
    },
    {
      id: "fm-yew",
      name: "Yew logs on a bonfire",
      minLevel: 60,
      maxLevel: 75,
      xpPerHour: 200000,
      intensity: "afk",
      members: true,
      wiki: "Yew tree",
    },
    {
      id: "fm-magic",
      name: "Magic logs on a bonfire",
      minLevel: 75,
      maxLevel: 90,
      xpPerHour: 280000,
      intensity: "afk",
      members: true,
      wiki: "Magic logs",
    },
    {
      id: "fm-elder",
      name: "Elder logs on a bonfire",
      minLevel: 90,
      xpPerHour: 400000,
      intensity: "afk",
      members: true,
      wiki: "Elder logs",
      note: "Stays the standard all the way to the 110 cap — Firemaking has no separate tier-100 method, just more expensive logs.",
    },
  ],

  // --- 12 Crafting (cap 110) ----------------------------------------------
  12: [
    {
      id: "cra-gems",
      name: "Cutting sapphires and emeralds",
      minLevel: 1,
      maxLevel: 55,
      xpPerHour: 40000,
      intensity: "moderate",
      members: false,
      wiki: "Sapphire",
    },
    {
      id: "cra-dragonstone",
      name: "Cutting and mounting dragonstones",
      minLevel: 55,
      maxLevel: 75,
      xpPerHour: 120000,
      intensity: "moderate",
      members: true,
      wiki: "Dragonstone",
    },
    {
      id: "cra-harps",
      name: "Playing crystal harps",
      minLevel: 75,
      xpPerHour: 60000,
      intensity: "afk",
      members: true,
      wiki: "Ithell Clan",
      note: "Prifddinas, needs Plague's End. Genuinely zero-cost and near-zero attention — the AFK option, not the fast one.",
    },
    {
      id: "cra-dhide",
      name: "Black dragonhide bodies",
      minLevel: 84,
      maxLevel: 100,
      xpPerHour: 250000,
      intensity: "moderate",
      members: true,
      wiki: "Black dragonhide",
      note: "Use a portable crafter for the extra hides-saved chance.",
    },
    {
      id: "cra-sandstone",
      name: "Red and crystal sandstone",
      minLevel: 89,
      maxLevel: 110,
      xpPerHour: 180000,
      gpPerHour: 1500000,
      intensity: "moderate",
      members: true,
      wiki: "Red sandstone",
      note: "The profitable option — this is a money method that happens to give Crafting XP.",
    },
    {
      id: "cra-starbloom",
      name: "Starbloom equipment",
      minLevel: 100,
      xpPerHour: 320000,
      intensity: "moderate",
      members: true,
      wiki: "Starbloom",
      note: "Opening method of the tier-100 band.",
    },
    {
      id: "cra-exquisite-urns",
      name: "Exquisite urns",
      minLevel: 102,
      xpPerHour: 350000,
      intensity: "moderate",
      members: true,
      wiki: "Exquisite urn",
      note: "Rate conservative; urn XP depends on how promptly you teleport them.",
    },
  ],

  // --- 13 Smithing (cap 110) ----------------------------------------------
  // Burial armour at the Artisans' Workshop is the whole skill from 40 up: no
  // material loss, no banking, and the XP scales with the bar tier you unlock.
  13: [
    {
      id: "smi-bronze",
      name: "Bronze and iron items",
      minLevel: 1,
      maxLevel: 40,
      xpPerHour: 30000,
      intensity: "moderate",
      members: false,
      wiki: "Smithing",
    },
    {
      id: "smi-adamant-burial",
      name: "Adamant burial armour",
      minLevel: 40,
      maxLevel: 70,
      xpPerHour: 120000,
      intensity: "moderate",
      members: true,
      wiki: "Burial armour",
      note: "Artisans' Workshop. Burial smithing consumes no extra materials and never needs banking.",
    },
    {
      id: "smi-necronium-burial",
      name: "Necronium burial armour",
      minLevel: 70,
      maxLevel: 80,
      xpPerHour: 170000,
      intensity: "moderate",
      members: true,
      wiki: "Necronium bar",
    },
    {
      id: "smi-bane-burial",
      name: "Bane burial armour",
      minLevel: 80,
      maxLevel: 90,
      xpPerHour: 220000,
      intensity: "moderate",
      members: true,
      wiki: "Artisans' Workshop",
    },
    {
      id: "smi-elder-burial",
      name: "Elder rune burial armour",
      minLevel: 90,
      maxLevel: 110,
      xpPerHour: 300000,
      intensity: "moderate",
      members: true,
      wiki: "Elder rune bar",
      note: "The workhorse from 90 to the cap.",
    },
    {
      id: "smi-masterwork",
      name: "Masterwork armour",
      minLevel: 99,
      xpPerHour: 200000,
      gpPerHour: 2500000,
      intensity: "click-intensive",
      members: true,
      wiki: "Masterwork armour",
      note: "Slower than burial but the only Smithing that pays — a long multi-stage process, not an AFK loop.",
    },
    {
      id: "smi-primal",
      name: "Primal bars and armour",
      minLevel: 100,
      xpPerHour: 380000,
      intensity: "moderate",
      members: true,
      wiki: "Primal bar",
      note: "Tier-100 band, fed by primal ore from Mining. Rate conservative.",
    },
  ],

  // --- 14 Mining (cap 110) ------------------------------------------------
  14: [
    {
      id: "min-copper-iron",
      name: "Copper, tin and iron",
      minLevel: 1,
      maxLevel: 20,
      xpPerHour: 30000,
      intensity: "moderate",
      members: false,
      wiki: "Mining Guild",
    },
    {
      id: "min-coal-mith",
      name: "Coal through mithril",
      minLevel: 20,
      maxLevel: 50,
      xpPerHour: 45000,
      intensity: "moderate",
      members: false,
      wiki: "Mining",
    },
    {
      id: "min-conc-coal",
      name: "Concentrated coal (Living Rock Caverns)",
      minLevel: 50,
      maxLevel: 70,
      xpPerHour: 75000,
      gpPerHour: 400000,
      intensity: "moderate",
      members: true,
      wiki: "Living Rock Caverns",
    },
    {
      id: "min-necrite",
      name: "Phasmatite and necrite",
      minLevel: 70,
      maxLevel: 81,
      xpPerHour: 95000,
      gpPerHour: 600000,
      intensity: "moderate",
      members: true,
      wiki: "Necrite",
    },
    {
      id: "min-banite",
      name: "Banite",
      minLevel: 80,
      maxLevel: 89,
      xpPerHour: 115000,
      gpPerHour: 900000,
      intensity: "moderate",
      members: true,
      wiki: "Banite",
    },
    {
      id: "min-red-sandstone",
      name: "Red sandstone",
      minLevel: 81,
      xpPerHour: 70000,
      gpPerHour: 1500000,
      intensity: "afk",
      members: true,
      wiki: "Red sandstone",
      note: "Poor XP, excellent money, and very AFK. Feeds the Crafting sandstone method.",
    },
    {
      id: "min-seren-stone",
      name: "Seren stones",
      minLevel: 89,
      maxLevel: 110,
      xpPerHour: 100000,
      intensity: "afk",
      members: true,
      wiki: "Seren stone",
      note: "No ore, no banking, no clicks — the AFK benchmark for high-level Mining.",
    },
    {
      id: "min-corrupted-ore",
      name: "Corrupted ore",
      minLevel: 89,
      maxLevel: 97,
      xpPerHour: 135000,
      intensity: "moderate",
      members: true,
      wiki: "Corrupted ore",
      note: "Corrupted seren stones: better XP than plain seren stones, at the cost of actual attention.",
    },
    {
      id: "min-animica",
      name: "Light and dark animica",
      minLevel: 90,
      maxLevel: 97,
      xpPerHour: 130000,
      gpPerHour: 1400000,
      intensity: "moderate",
      members: true,
      wiki: "Dark animica",
      note: "Empyrean Citadel or Anachronia. The best XP-and-GP compromise before 97.",
    },
    {
      id: "min-alaea",
      name: "Alaea crablets",
      minLevel: 97,
      maxLevel: 100,
      xpPerHour: 160000,
      intensity: "click-intensive",
      members: true,
      wiki: "Alaea crablet",
    },
    {
      id: "min-primal",
      name: "Primal rocks",
      minLevel: 100,
      xpPerHour: 200000,
      intensity: "moderate",
      members: true,
      wiki: "Primal rocks",
      note: "The 100-110 band; primal ore is what Smithing's primal tier is built from. Rate conservative.",
    },
  ],

  // --- 15 Herblore (cap 120) ----------------------------------------------
  15: [
    {
      id: "her-unf",
      name: "Unfinished potions",
      minLevel: 1,
      maxLevel: 19,
      xpPerHour: 80000,
      intensity: "moderate",
      members: true,
      wiki: "Unfinished potion",
    },
    {
      id: "her-tar",
      name: "Harralander tar",
      minLevel: 19,
      xpPerHour: 450000,
      intensity: "click-intensive",
      members: true,
      wiki: "Harralander tar",
      note: "Technically the fastest Herblore XP at ANY level once Lunar Diplomacy is done — but it is pure cost with no usable output.",
    },
    {
      id: "her-aggression",
      name: "Aggression potions",
      minLevel: 82,
      maxLevel: 96,
      xpPerHour: 320000,
      gpPerHour: 600000,
      intensity: "moderate",
      members: true,
      wiki: "Aggression potion",
      note: "The sensible mid-tier pick: fast, and the potions actually sell.",
    },
    {
      id: "her-overloads",
      name: "Overloads",
      minLevel: 96,
      maxLevel: 99,
      xpPerHour: 400000,
      intensity: "moderate",
      members: true,
      wiki: "Overload",
    },
    {
      id: "her-poison-bombs",
      name: "Poison bombs",
      minLevel: 99,
      maxLevel: 101,
      xpPerHour: 420000,
      intensity: "moderate",
      members: true,
      wiki: "Poison bomb",
      note: "950 XP each; about 3,000 bombs covers 99-101.",
    },
    {
      id: "her-elder-overload",
      name: "Elder overload potions",
      minLevel: 106,
      xpPerHour: 450000,
      intensity: "moderate",
      members: true,
      wiki: "Elder overload potion",
      note: "You want these for combat anyway — making your own is the rare case where the XP is a free by-product.",
    },
    {
      id: "her-sticky-bombs",
      name: "Sticky bombs",
      minLevel: 101,
      maxLevel: 107,
      xpPerHour: 450000,
      intensity: "moderate",
      members: true,
      wiki: "Sticky bomb",
      note: "1,000 XP each; roughly 12,900 bombs across the band.",
    },
    {
      id: "her-vuln-bombs",
      name: "Vulnerability bombs",
      minLevel: 107,
      xpPerHour: 480000,
      intensity: "moderate",
      members: true,
      wiki: "Vulnerability bomb",
      note: "1,100 XP each — and about 51,600 of them to reach 118. This is the 120 Herblore grind.",
    },
  ],

  // --- 16 Agility (cap 99) ------------------------------------------------
  16: [
    {
      id: "agi-gnome",
      name: "Gnome Stronghold course",
      minLevel: 1,
      maxLevel: 30,
      xpPerHour: 20000,
      intensity: "click-intensive",
      members: true,
      wiki: "Gnome Stronghold Agility Course",
    },
    {
      id: "agi-clockwork",
      name: "Clockwork suits",
      minLevel: 30,
      maxLevel: 50,
      xpPerHour: 45000,
      intensity: "moderate",
      members: true,
      wiki: "Clockwork suit",
    },
    {
      id: "agi-anachronia-novice",
      name: "Anachronia course (novice)",
      minLevel: 50,
      maxLevel: 52,
      xpPerHour: 55000,
      intensity: "click-intensive",
      members: true,
      wiki: "Anachronia Agility Course",
    },
    {
      id: "agi-wilderness",
      name: "Wilderness Agility Course",
      minLevel: 52,
      maxLevel: 80,
      xpPerHour: 65000,
      intensity: "click-intensive",
      members: true,
      wiki: "Wilderness Agility Course",
      note: "Still the long middle of the skill. You will get PKed occasionally; bring nothing.",
    },
    {
      id: "agi-hets-oasis",
      name: "Het's Oasis course",
      minLevel: 65,
      maxLevel: 77,
      xpPerHour: 60000,
      intensity: "moderate",
      members: true,
      wiki: "Het's Oasis Agility Course",
      note: "Safe alternative to the Wilderness for the same band.",
    },
    {
      id: "agi-serenity",
      name: "Serenity posts",
      minLevel: 75,
      xpPerHour: 40000,
      intensity: "afk",
      members: true,
      wiki: "Serenity post",
      note: "Prifddinas. Low rate, but it is the closest Agility gets to AFK.",
    },
    {
      id: "agi-anachronia-island",
      name: "Island-wide Anachronia course",
      minLevel: 80,
      xpPerHour: 90000,
      intensity: "click-intensive",
      members: true,
      wiki: "Anachronia Agility Course",
      note: "85 unlocks the full island route; the best Agility rate to 99.",
    },
    {
      id: "agi-silverhawks",
      name: "Silverhawk boots (passive)",
      minLevel: 1,
      xpPerHour: 55000,
      intensity: "afk",
      members: true,
      wiki: "Silverhawk boots",
      note: "Not a method — passive XP while you do anything else. Most accounts get most of their Agility this way.",
    },
  ],

  // --- 17 Thieving (cap 120) ----------------------------------------------
  17: [
    {
      id: "thi-stalls",
      name: "Stalls and low pickpocketing",
      minLevel: 1,
      maxLevel: 35,
      xpPerHour: 30000,
      intensity: "moderate",
      members: true,
      wiki: "Thieving",
    },
    {
      id: "thi-afk-pickpocket",
      name: "Low-level AFK pickpocketing",
      minLevel: 35,
      maxLevel: 62,
      xpPerHour: 90000,
      intensity: "afk",
      members: true,
      wiki: "Thieving",
    },
    {
      id: "thi-pyramid-plunder",
      name: "Pyramid Plunder",
      minLevel: 51,
      maxLevel: 91,
      xpPerHour: 300000,
      gpPerHour: 400000,
      intensity: "click-intensive",
      members: true,
      wiki: "Pyramid Plunder",
      note: "Room 4 opens at 51, the last room at 91. Still respectable, but Safecracking has largely replaced it.",
    },
    {
      id: "thi-safecracking",
      name: "Safecracking (Misthalin to Kandarin)",
      minLevel: 62,
      maxLevel: 95,
      xpPerHour: 350000,
      gpPerHour: 1000000,
      intensity: "moderate",
      members: true,
      wiki: "Safecracking",
      note: "The modern spine of the skill: Misthalin 62, Asgarnia 76, Kandarin 83, hidden safes 90.",
    },
    {
      id: "thi-shifting-tombs",
      name: "Shifting Tombs",
      minLevel: 70,
      maxLevel: 99,
      xpPerHour: 250000,
      intensity: "click-intensive",
      members: true,
      wiki: "Shifting Tombs",
      note: "Tiers at 50/70/90 across the four Menaphos skills — good when you want Thieving and Agility together.",
    },
    {
      id: "thi-vault",
      name: "Vault of Hereditas heist",
      minLevel: 95,
      maxLevel: 108,
      xpPerHour: 450000,
      gpPerHour: 2000000,
      intensity: "click-intensive",
      members: true,
      wiki: "Vault of Hereditas",
      note: "Heists are the 95-120 content. Rate assumes you know the route.",
    },
    {
      id: "thi-elven-workers",
      name: "Pickpocketing elven clan workers",
      minLevel: 96,
      xpPerHour: 320000,
      gpPerHour: 900000,
      intensity: "moderate",
      members: true,
      wiki: "Prifddinas",
      note: "The steady alternative to heists — far less thinking per hour.",
    },
    {
      id: "thi-asuran-arsenal",
      name: "Asuran Arsenal heist",
      minLevel: 108,
      xpPerHour: 550000,
      gpPerHour: 3000000,
      intensity: "click-intensive",
      members: true,
      wiki: "Asuran Arsenal",
      note: "Top of the skill. Conservative rate — heist throughput varies enormously with execution.",
    },
  ],

  // --- 18 Slayer (cap 120) ------------------------------------------------
  // Slayer XP is master-gated more than method-gated: the right question is
  // always "am I on the highest master I can survive", not "what do I kill".
  18: [
    {
      id: "sla-low-masters",
      name: "Turael through Vannaka tasks",
      minLevel: 1,
      maxLevel: 55,
      xpPerHour: 25000,
      intensity: "moderate",
      members: true,
      wiki: "Slayer Tower",
    },
    {
      id: "sla-tower",
      name: "Slayer Tower tasks",
      minLevel: 55,
      maxLevel: 75,
      xpPerHour: 50000,
      intensity: "moderate",
      members: true,
      wiki: "Slayer Tower",
    },
    {
      id: "sla-kuradal",
      name: "Kuradal tasks",
      minLevel: 75,
      maxLevel: 85,
      xpPerHour: 75000,
      gpPerHour: 1000000,
      intensity: "moderate",
      members: true,
      wiki: "Kuradal",
    },
    {
      id: "sla-morvran",
      name: "Morvran tasks",
      minLevel: 85,
      maxLevel: 99,
      xpPerHour: 110000,
      gpPerHour: 2000000,
      intensity: "moderate",
      members: true,
      wiki: "Morvran",
      note: "Prifddinas; the standard high-level master and where Slayer starts paying properly.",
    },
    {
      id: "sla-laniakea",
      name: "Laniakea tasks",
      minLevel: 90,
      xpPerHour: 130000,
      gpPerHour: 2200000,
      intensity: "moderate",
      members: true,
      wiki: "Laniakea",
      note: "Anachronia. Assigns the dinosaur tasks Morvran cannot.",
    },
    {
      id: "sla-abyssal",
      name: "Abyssal Slayer creatures",
      minLevel: 95,
      xpPerHour: 200000,
      gpPerHour: 3000000,
      intensity: "moderate",
      members: true,
      wiki: "Abyssal Slayer creatures",
      note: "Savages 95, beasts 105, lords 115 — the ladder that carries you to 120.",
    },
    {
      id: "sla-sunken-pyramid",
      name: "Sunken Pyramid",
      minLevel: 100,
      xpPerHour: 180000,
      intensity: "moderate",
      members: true,
      wiki: "Sunken Pyramid",
      note: "Pairs with the Slayer Codex for the collection-log side of the skill.",
    },
  ],

  // --- 19 Farming (cap 120) -----------------------------------------------
  // Farming is a run-based skill: the "xp per hour" figures assume you count
  // only the minutes spent doing the run, not the 80 minutes of growth.
  19: [
    {
      id: "far-manure-mound",
      name: "Manure mound",
      minLevel: 1,
      maxLevel: 7,
      xpPerHour: 3750,
      intensity: "moderate",
      members: true,
      wiki: "Manure mound",
    },
    {
      id: "far-seedicide",
      name: "Seedicide (passive)",
      minLevel: 7,
      xpPerHour: 20000,
      intensity: "afk",
      members: true,
      wiki: "Seedicide",
      note: "Passive XP from seeds destroyed while you fight — around 250k/hr at 74 if you are killing constantly.",
    },
    {
      id: "far-herb-runs",
      name: "Herb runs",
      minLevel: 32,
      xpPerHour: 60000,
      gpPerHour: 400000,
      intensity: "moderate",
      members: true,
      wiki: "Herb patch",
      note: "Per-run rate, not per real hour. Ranarr from 32, torstol from 85.",
    },
    {
      id: "far-hets-oasis",
      name: "Het's Oasis",
      minLevel: 30,
      maxLevel: 86,
      xpPerHour: 50000,
      intensity: "moderate",
      members: true,
      wiki: "Het's Oasis",
      note: "Scales from ~15k at 30 to ~100k at 86.",
    },
    {
      id: "far-tree-runs",
      name: "Tree and fruit tree runs",
      minLevel: 60,
      xpPerHour: 200000,
      intensity: "moderate",
      members: true,
      wiki: "Magic tree",
      note: "The backbone of the skill. Magic trees from 75, elder from 90.",
    },
    {
      id: "far-rumberry",
      name: "Foraging rumberry bushes",
      minLevel: 86,
      maxLevel: 94,
      xpPerHour: 30000,
      intensity: "afk",
      members: true,
      wiki: "Rumberry",
    },
    {
      id: "far-mushroom-clusters",
      name: "Foraging mushroom clusters",
      minLevel: 94,
      maxLevel: 109,
      xpPerHour: 50000,
      intensity: "afk",
      members: true,
      wiki: "Mushroom cluster",
    },
    {
      id: "far-dinosaur-farm",
      name: "Anachronia Dinosaur Farm",
      minLevel: 90,
      xpPerHour: 120000,
      gpPerHour: 800000,
      intensity: "moderate",
      members: true,
      wiki: "Anachronia Dinosaur Farm",
      note: "Run-based like everything else here; the big-ticket animals are the payoff.",
    },
    {
      id: "far-guarana",
      name: "Guarana trees",
      minLevel: 107,
      maxLevel: 113,
      xpPerHour: 220000,
      intensity: "moderate",
      members: true,
      wiki: "Guarana tree",
    },
    {
      id: "far-tombshrooms",
      name: "Tombshrooms",
      minLevel: 109,
      xpPerHour: 200000,
      intensity: "moderate",
      members: true,
      wiki: "Tombshroom",
    },
    {
      id: "far-carambola",
      name: "Carambola trees",
      minLevel: 113,
      xpPerHour: 260000,
      intensity: "moderate",
      members: true,
      wiki: "Carambola tree",
      note: "The last farming unlock before 120.",
    },
  ],

  // --- 20 Runecrafting (cap 110) ------------------------------------------
  20: [
    {
      id: "rc-runespan-low",
      name: "Runespan (low platform)",
      minLevel: 1,
      maxLevel: 33,
      xpPerHour: 25000,
      intensity: "moderate",
      members: true,
      wiki: "Runespan",
      note: "No runes, no essence, no profit — but it is the whole skill for most players.",
    },
    {
      id: "rc-runespan-mid",
      name: "Runespan (middle platform)",
      minLevel: 33,
      maxLevel: 66,
      xpPerHour: 55000,
      intensity: "moderate",
      members: true,
      wiki: "Runespan",
    },
    {
      id: "rc-runespan-high",
      name: "Runespan (top platform)",
      minLevel: 66,
      xpPerHour: 100000,
      intensity: "moderate",
      members: true,
      wiki: "Runespan",
      note: "Stays the fastest XP right to the 110 cap. Everything below is chosen for money instead.",
    },
    {
      id: "rc-ourania",
      name: "Ourania (ZMI) altar",
      minLevel: 1,
      xpPerHour: 60000,
      gpPerHour: 700000,
      intensity: "click-intensive",
      members: true,
      wiki: "Ourania Runecrafting Altar",
      note: "Mixed rune output scaled to your level — the XP-and-GP compromise.",
    },
    {
      id: "rc-natures",
      name: "Nature runes via the Abyss",
      minLevel: 77,
      xpPerHour: 80000,
      gpPerHour: 1200000,
      intensity: "click-intensive",
      members: true,
      wiki: "Abyss",
      note: "Needs Enter the Abyss (miniquest). Wilderness exposure is the cost.",
    },
    {
      id: "rc-souls",
      name: "Soul runes",
      minLevel: 90,
      xpPerHour: 95000,
      gpPerHour: 2000000,
      intensity: "moderate",
      members: true,
      wiki: "Soul altar",
      note: "The best Runecrafting money at high level, and the reason 90 matters.",
    },
  ],

  // --- 21 Hunter (cap 110) ------------------------------------------------
  21: [
    {
      id: "hun-crimson-swift",
      name: "Crimson swifts and cerulean twitches",
      minLevel: 1,
      maxLevel: 19,
      xpPerHour: 15000,
      intensity: "moderate",
      members: true,
      wiki: "Crimson swift",
    },
    {
      id: "hun-birdhouses",
      name: "Birdhouse runs",
      minLevel: 5,
      xpPerHour: 30000,
      intensity: "afk",
      members: true,
      wiki: "Birdhouse",
      note: "A few minutes every 50 minutes, from level 5 to the cap. Set it and forget it.",
    },
    {
      id: "hun-gliding-whirligigs",
      name: "Gliding whirligigs",
      minLevel: 30,
      maxLevel: 50,
      xpPerHour: 60000,
      intensity: "moderate",
      members: true,
      wiki: "Gliding whirligig",
    },
    {
      id: "hun-chinchompas",
      name: "Red chinchompas",
      minLevel: 63,
      maxLevel: 80,
      xpPerHour: 140000,
      gpPerHour: 900000,
      intensity: "moderate",
      members: true,
      wiki: "Red chinchompa",
      note: "Still the classic — good XP and the chins sell for Ranged training.",
    },
    {
      id: "hun-swift-whirligigs",
      name: "Swift and hasty whirligigs",
      minLevel: 50,
      maxLevel: 90,
      xpPerHour: 130000,
      intensity: "moderate",
      members: true,
      wiki: "Swift whirligig",
      note: "The whirligig ladder is the straight-line XP path: swift 50, hasty 70, speedy 90.",
    },
    {
      id: "hun-big-game",
      name: "Big Game Hunter",
      minLevel: 75,
      xpPerHour: 180000,
      intensity: "click-intensive",
      members: true,
      wiki: "Big Game Hunter",
      note: "Anachronia. Involved setup per kill, but it is a real fight rather than a trap loop.",
    },
    {
      id: "hun-grenwalls",
      name: "Grenwalls with Crystallise",
      minLevel: 77,
      maxLevel: 96,
      xpPerHour: 220000,
      gpPerHour: 700000,
      intensity: "click-intensive",
      members: true,
      wiki: "Grenwall",
      note: "Crystallise roughly doubles the rate and is what makes this competitive.",
    },
    {
      id: "hun-charming-moths",
      name: "Charming moths",
      minLevel: 88,
      maxLevel: 96,
      xpPerHour: 190000,
      intensity: "moderate",
      members: true,
      wiki: "Charming moth",
      note: "Also produces Summoning charms — the one Hunter method that feeds another skill.",
    },
    {
      id: "hun-speedy-whirligigs",
      name: "Speedy whirligigs",
      minLevel: 90,
      xpPerHour: 200000,
      intensity: "moderate",
      members: true,
      wiki: "Speedy whirligig",
    },
    {
      id: "hun-decaying-guards",
      name: "Decaying guards",
      minLevel: 92,
      xpPerHour: 240000,
      intensity: "moderate",
      members: true,
      wiki: "Decaying guard",
      note: "Carries to the 110 cap. Rate conservative.",
    },
  ],

  // --- 22 Construction (cap 99) -------------------------------------------
  // NOTE: the app caps Construction at 99 (lib/skills.ts). The 2026
  // Construction update added eternal furniture above that; nothing here goes
  // past 99 so the ladder stays consistent with the rest of the app.
  22: [
    {
      id: "con-wooden",
      name: "Wooden furniture",
      minLevel: 1,
      maxLevel: 33,
      xpPerHour: 60000,
      intensity: "click-intensive",
      members: true,
      wiki: "Player-owned house",
      note: "Needs There's No Place Like Home. New Foundations alone grants enough XP to skip most of this band.",
    },
    {
      id: "con-oak-larders",
      name: "Oak larders",
      minLevel: 33,
      maxLevel: 56,
      xpPerHour: 180000,
      intensity: "click-intensive",
      members: true,
      wiki: "Oak larder",
      note: "Best rate for a long stretch, and oak gets a 50% build-speed bonus at 70.",
    },
    {
      id: "con-contracts",
      name: "Construction Contracts",
      minLevel: 40,
      xpPerHour: 90000,
      intensity: "moderate",
      members: true,
      wiki: "Construction Contracts",
      note: "Far cheaper than furniture per XP. The right choice if planks, not time, are your constraint.",
    },
    {
      id: "con-teak-long-table",
      name: "Teak long tables",
      minLevel: 56,
      maxLevel: 72,
      xpPerHour: 280000,
      intensity: "click-intensive",
      members: true,
      wiki: "Teak long table",
    },
    {
      id: "con-mahogany-long-table",
      name: "Mahogany long tables",
      minLevel: 72,
      maxLevel: 80,
      xpPerHour: 400000,
      intensity: "click-intensive",
      members: true,
      wiki: "Mahogany long table",
      note: "Also the cheap fallback from 99 upward if you skip potion cauldrons.",
    },
    {
      id: "con-potion-cauldron",
      name: "Basic potion cauldrons",
      minLevel: 80,
      xpPerHour: 480000,
      intensity: "click-intensive",
      members: true,
      wiki: "Potion cauldron",
      note: "Added in the 2026 Construction update; fastest from 80 but noticeably more expensive than teak.",
    },
    {
      id: "con-fort-forinthry",
      name: "Fort Forinthry buildings",
      minLevel: 54,
      xpPerHour: 120000,
      intensity: "moderate",
      members: true,
      wiki: "Fort Forinthry",
      note: "One-off XP per building rather than a repeatable loop — treat it as a milestone, not a grind.",
    },
  ],

  // --- 23 Summoning (cap 99) ----------------------------------------------
  // Summoning is charm-limited, not level-limited: the ladder below is about
  // which pouch converts your charm stock most efficiently.
  23: [
    {
      id: "sum-spirit-terrorbird",
      name: "Spirit terrorbird pouches",
      minLevel: 52,
      maxLevel: 67,
      xpPerHour: 150000,
      intensity: "moderate",
      members: true,
      wiki: "Spirit terrorbird pouch",
    },
    {
      id: "sum-war-tortoise",
      name: "War tortoise pouches",
      minLevel: 67,
      maxLevel: 88,
      xpPerHour: 190000,
      intensity: "moderate",
      members: true,
      wiki: "War tortoise pouch",
    },
    {
      id: "sum-unicorn-stallion",
      name: "Unicorn stallion pouches",
      minLevel: 88,
      maxLevel: 96,
      xpPerHour: 210000,
      intensity: "moderate",
      members: true,
      wiki: "Unicorn stallion pouch",
    },
    {
      id: "sum-pack-yak",
      name: "Pack yak pouches",
      minLevel: 96,
      maxLevel: 99,
      xpPerHour: 230000,
      intensity: "moderate",
      members: true,
      wiki: "Pack yak pouch",
      note: "96, not 67 — the legacy data had this badly wrong. Also the best beast of burden in the game.",
    },
    {
      id: "sum-iron-titan",
      name: "Iron titan pouches",
      minLevel: 99,
      xpPerHour: 250000,
      intensity: "moderate",
      members: true,
      wiki: "Iron titan pouch",
    },
    {
      id: "sum-charm-farming",
      name: "Charm gathering (moths and drops)",
      minLevel: 1,
      xpPerHour: 0,
      intensity: "moderate",
      members: true,
      wiki: "Charming moth",
      note: "Zero direct XP — but charms are the actual bottleneck, so this is where the hours really go.",
    },
  ],

  // --- 24 Dungeoneering (cap 120) -----------------------------------------
  24: [
    {
      id: "dg-solo-small",
      name: "Solo small floors",
      minLevel: 1,
      maxLevel: 35,
      xpPerHour: 50000,
      intensity: "click-intensive",
      members: false,
      wiki: "Dungeoneering floor",
      note: "Dungeoneering is one of the few skills with meaningful free-to-play content.",
    },
    {
      id: "dg-sinkholes",
      name: "Sinkholes",
      minLevel: 35,
      xpPerHour: 280000,
      intensity: "click-intensive",
      members: true,
      wiki: "Sinkhole",
      note: "Daily D&D, not weekly — the legacy data was wrong. A ~7 minute burst, not a sustained method.",
    },
    {
      id: "dg-c6-5-5",
      name: "Complexity 6 large floors, 5:5",
      minLevel: 60,
      xpPerHour: 300000,
      intensity: "click-intensive",
      members: true,
      wiki: "Daemonheim",
      note: "The real 99-120 grind. Rate assumes a coordinated team; a random group is a fraction of this.",
    },
    {
      id: "dg-elite-dungeons",
      name: "Elite Dungeons",
      minLevel: 90,
      xpPerHour: 200000,
      gpPerHour: 4000000,
      intensity: "click-intensive",
      members: true,
      wiki: "Elite Dungeons",
      note: "Worse Dungeoneering XP than floors, but the combat XP and drops make it the better hour overall.",
    },
    {
      id: "dg-gorajan",
      name: "Floors in Gorajan trailblazer gear",
      minLevel: 99,
      xpPerHour: 380000,
      intensity: "click-intensive",
      members: true,
      wiki: "Gorajan trailblazer outfit",
      note: "The outfit's XP bonus is what makes the last 20 levels tolerable.",
    },
  ],

  // --- 25 Divination (cap 99) ---------------------------------------------
  25: [
    {
      id: "div-low-wisps",
      name: "Pale through gleaming wisps",
      minLevel: 1,
      maxLevel: 40,
      xpPerHour: 25000,
      intensity: "moderate",
      members: false,
      wiki: "Divination",
    },
    {
      id: "div-mid-wisps",
      name: "Vibrant through radiant wisps",
      minLevel: 40,
      maxLevel: 70,
      xpPerHour: 90000,
      gpPerHour: 300000,
      intensity: "moderate",
      members: true,
      wiki: "Divination",
    },
    {
      id: "div-hall-of-memories",
      name: "Hall of Memories",
      minLevel: 70,
      xpPerHour: 160000,
      intensity: "moderate",
      members: true,
      wiki: "Hall of Memories",
      note: "Also the source of the Divination outfit pieces, which pay for themselves.",
    },
    {
      id: "div-cursed-wisps",
      name: "Cursed wisps",
      minLevel: 85,
      xpPerHour: 170000,
      gpPerHour: 1500000,
      intensity: "moderate",
      members: true,
      wiki: "Cursed wisp",
      note: "Wilderness. Best Divination money by a wide margin; you will occasionally lose the energy.",
    },
    {
      id: "div-incandescent",
      name: "Incandescent wisps",
      minLevel: 85,
      xpPerHour: 250000,
      gpPerHour: 900000,
      intensity: "moderate",
      members: true,
      wiki: "Incandescent wisp",
      note: "The safe top-tier wisp and the default from 85 to 99.",
    },
    {
      id: "div-guthixian-cache",
      name: "Guthixian Cache",
      minLevel: 1,
      xpPerHour: 60000,
      intensity: "click-intensive",
      members: true,
      wiki: "Guthixian Cache",
      note: "Runs every hour; a few minutes of burst XP plus the Chronicle fragment unlock.",
    },
  ],

  // --- 26 Invention (cap 150) ---------------------------------------------
  // Invention XP overwhelmingly comes from levelling and disassembling gear you
  // were going to use anyway. Anything else is a rounding error.
  26: [
    {
      id: "inv-tutorial",
      name: "Early disassembly",
      minLevel: 1,
      maxLevel: 27,
      xpPerHour: 50000,
      intensity: "moderate",
      members: true,
      wiki: "Disassemble",
      note: "Requires 80 Crafting, 80 Divination and 80 Smithing to unlock the skill at all.",
    },
    {
      id: "inv-levelling-items",
      name: "Levelling and siphoning augmented gear",
      minLevel: 27,
      xpPerHour: 150000,
      intensity: "afk",
      members: true,
      wiki: "Equipment siphon",
      note: "Passive: train combat or a gathering skill in augmented gear, siphon at item level 10-12, repeat.",
    },
    {
      id: "inv-gizmos",
      name: "Creating and discarding gizmos",
      minLevel: 86,
      xpPerHour: 220000,
      intensity: "moderate",
      members: true,
      wiki: "Invention",
      note: "Direct XP for materials — the option when you want Invention levels now rather than eventually.",
    },
    {
      id: "inv-ancient",
      name: "Ancient Invention",
      minLevel: 80,
      xpPerHour: 250000,
      intensity: "moderate",
      members: true,
      wiki: "Ancient Invention",
      note: "Needs Desperate Times. Unlocks ancient gizmos and the higher-tier perks worth having.",
    },
    {
      id: "inv-charge-packs",
      name: "Divine charge production",
      minLevel: 80,
      xpPerHour: 100000,
      gpPerHour: 1000000,
      intensity: "moderate",
      members: true,
      wiki: "Divine charge",
      note: "Modest XP, but it feeds every augmented item you own.",
    },
    {
      id: "inv-capacitor",
      name: "XP Capacitor 5000",
      minLevel: 99,
      xpPerHour: 0,
      intensity: "moderate",
      members: true,
      wiki: "XP Capacitor 5000",
      note: "Not an hourly method — a device that converts stored equipment XP into a lump of Invention XP.",
    },
  ],

  // --- 27 Archaeology (cap 120) -------------------------------------------
  // Levels below are dig-site unlock levels taken from the Archaeology page.
  // The XP rate inside a site climbs steadily as you unlock deeper materials.
  27: [
    {
      id: "arc-kharid-et",
      name: "Kharid-et excavation",
      minLevel: 5,
      maxLevel: 20,
      xpPerHour: 30000,
      intensity: "moderate",
      members: true,
      wiki: "Kharid-et",
    },
    {
      id: "arc-infernal-source",
      name: "Infernal Source excavation",
      minLevel: 20,
      maxLevel: 42,
      xpPerHour: 50000,
      intensity: "moderate",
      members: true,
      wiki: "Infernal Source",
    },
    {
      id: "arc-everlight",
      name: "Everlight excavation",
      minLevel: 42,
      maxLevel: 70,
      xpPerHour: 80000,
      intensity: "moderate",
      members: true,
      wiki: "Everlight",
    },
    {
      id: "arc-stormguard",
      name: "Stormguard Citadel excavation",
      minLevel: 70,
      maxLevel: 76,
      xpPerHour: 110000,
      intensity: "moderate",
      members: true,
      wiki: "Stormguard Citadel",
    },
    {
      id: "arc-warforge",
      name: "Warforge excavation",
      minLevel: 76,
      maxLevel: 89,
      xpPerHour: 130000,
      intensity: "moderate",
      members: true,
      wiki: "Warforge",
    },
    {
      id: "arc-senntisten",
      name: "Senntisten excavation",
      minLevel: 89,
      xpPerHour: 160000,
      gpPerHour: 700000,
      intensity: "moderate",
      members: true,
      wiki: "Senntisten",
      note: "Level is the commonly cited unlock; treat it as approximate.",
    },
    {
      id: "arc-orthen",
      name: "Orthen excavation",
      minLevel: 105,
      xpPerHour: 200000,
      gpPerHour: 1200000,
      intensity: "moderate",
      members: true,
      wiki: "Orthen",
      note: "The newest site and the 105-120 band. Unlock level cited from the dig site page rather than measured.",
    },
    {
      id: "arc-screening",
      name: "Screening soil (passive)",
      minLevel: 5,
      xpPerHour: 25000,
      intensity: "afk",
      members: true,
      wiki: "Screening",
      note: "Layered on top of excavation, not instead of it.",
    },
  ],

  // --- 28 Necromancy (cap 120) --------------------------------------------
  28: [
    {
      id: "nec-um-ghosts",
      name: "Ghosts in the City of Um",
      minLevel: 1,
      maxLevel: 30,
      xpPerHour: 45000,
      intensity: "moderate",
      members: false,
      wiki: "City of Um",
      note: "The starting area from the Necromancy! quest.",
    },
    {
      id: "nec-rituals-low",
      name: "Low-level rituals",
      minLevel: 20,
      maxLevel: 70,
      xpPerHour: 70000,
      intensity: "moderate",
      members: true,
      wiki: "Ritual site",
      note: "Rituals are the non-combat half of Necromancy and the only way to get some materials.",
    },
    {
      id: "nec-slayer",
      name: "Slayer tasks with Necromancy",
      minLevel: 30,
      maxLevel: 90,
      xpPerHour: 150000,
      intensity: "moderate",
      members: true,
      wiki: "Slayer Tower",
      note: "Necromancy is strong and cheap at every tier — most players level it purely through Slayer.",
    },
    {
      id: "nec-ripper-demons",
      name: "Ripper demons",
      minLevel: 80,
      maxLevel: 99,
      xpPerHour: 280000,
      intensity: "click-intensive",
      members: true,
      wiki: "Ripper Demon",
    },
    {
      id: "nec-high-rituals",
      name: "High-level rituals",
      minLevel: 90,
      xpPerHour: 200000,
      intensity: "moderate",
      members: true,
      wiki: "Ritual site",
      note: "The 90-120 ritual band. Slower than combat but entirely safe and semi-AFK.",
    },
    {
      id: "nec-rasial",
      name: "Rasial, the First Necromancer",
      minLevel: 90,
      xpPerHour: 400000,
      gpPerHour: 9000000,
      intensity: "click-intensive",
      members: true,
      wiki: "Rasial, the First Necromancer",
      note: "The capstone Necromancy boss and the source of the tier-95 gear. Rate assumes a clean kill loop.",
    },
    {
      id: "nec-arch-glacor",
      name: "Arch-Glacor (normal mode)",
      minLevel: 99,
      xpPerHour: 420000,
      intensity: "moderate",
      members: true,
      wiki: "Arch-Glacor",
      note: "The steady 99-120 option when you do not want Rasial's intensity.",
    },
  ],
};

// ---------------------------------------------------------------------------
// UNLOCKS — levels that open something you would actually plan around.
//
// Ported from the legacy NS_UNLOCKS (with the wrong entries corrected) and
// extended into the 90-120 band, which the legacy list did not reach at all.
// ---------------------------------------------------------------------------

export const UNLOCKS: SkillUnlock[] = [
  // --- Combat -------------------------------------------------------------
  { skill: 0, level: 60, label: "Dragon weapons", blurb: "Tier 60 melee. The first weapon upgrade that feels like one.", wiki: "Attack" },
  { skill: 0, level: 80, label: "Drygore weapons", blurb: "Tier 90 melee — the long-lived endgame melee mainhand.", wiki: "Attack" },
  { skill: 0, level: 92, label: "Masterwork spear of annihilation", blurb: "Tier 92 melee, and the last melee weapon most accounts ever need.", wiki: "Masterwork armour" },
  { skill: 1, level: 85, label: "Tetsu and Death Lotus armour", blurb: "Tier 85 armour from the Player-owned port.", wiki: "Defence" },
  { skill: 1, level: 90, label: "Tier 90 power armour", blurb: "Malevolent, Sirenic and Tectonic all gate here.", wiki: "Defence" },
  { skill: 2, level: 60, label: "Dragon weapons", blurb: "Strength side of the tier 60 gate.", wiki: "Strength" },
  { skill: 3, level: 99, label: "Constitution 99", blurb: "9,900 life points before any bonuses — the survivability floor for endgame bossing.", wiki: "Constitution" },
  { skill: 4, level: 76, label: "Death's Swiftness", blurb: "The Ranged ultimate from The World Wakes. Doubles your damage window.", wiki: "Ranged" },
  { skill: 4, level: 90, label: "Ascension crossbows and Sirenic", blurb: "Tier 90 Ranged weapon and armour.", wiki: "Ranged" },
  { skill: 6, level: 76, label: "Sunshine", blurb: "The Magic ultimate from The World Wakes.", wiki: "Magic" },
  { skill: 6, level: 90, label: "Seismic weaponry and Tectonic", blurb: "Tier 90 Magic weapon and armour.", wiki: "Magic" },
  { skill: 6, level: 95, label: "Ancient Magicks upgrades", blurb: "The high-tier spell tiers that make Magic competitive again at the top end.", wiki: "Magic" },
  { skill: 5, level: 95, label: "Overcharged and turmoil-tier prayers", blurb: "The prayer book that endgame DPS assumes you have.", wiki: "Prayer" },
  { skill: 5, level: 99, label: "Prayer 99", blurb: "Skillcape of Prayer, and every curse unlocked.", wiki: "Prayer" },
  { skill: 28, level: 80, label: "Phantom Guardian", blurb: "Well of Souls tier-5 talent — the practical floor where players invest in it.", wiki: "Necromancy" },
  { skill: 28, level: 90, label: "Rasial", blurb: "The capstone Necromancy boss and the tier-95 Necromancy gear behind it.", wiki: "Rasial, the First Necromancer" },
  { skill: 28, level: 99, label: "Necromancy 99", blurb: "Full talent tree access and the Necromancy cape.", wiki: "Necromancy" },
  { skill: 28, level: 120, label: "Necromancy 120", blurb: "Master cape. The highest-value 120 in the game for pure combat throughput.", wiki: "Necromancy" },

  // --- Slayer -------------------------------------------------------------
  { skill: 18, level: 75, label: "Abyssal demon tasks", blurb: "Whips, and the first Slayer task worth camping.", wiki: "Abyssal demon" },
  { skill: 18, level: 85, label: "Morvran", blurb: "Prifddinas Slayer master — where Slayer starts paying for itself.", wiki: "Morvran" },
  { skill: 18, level: 90, label: "Laniakea", blurb: "Anachronia Slayer master and the dinosaur task list.", wiki: "Laniakea" },
  { skill: 18, level: 95, label: "Abyssal savages", blurb: "Entry to the abyssal creature ladder that carries Slayer to 120.", wiki: "Abyssal Slayer creatures" },
  { skill: 18, level: 105, label: "Abyssal beasts", blurb: "Second rung of the abyssal ladder.", wiki: "Abyssal Slayer creatures" },
  { skill: 18, level: 115, label: "Abyssal lords", blurb: "Top Slayer creature in the game.", wiki: "Abyssal Slayer creatures" },
  { skill: 18, level: 120, label: "Slayer 120", blurb: "Master cape and every assignment unlocked.", wiki: "Slayer" },

  // --- Gathering ----------------------------------------------------------
  { skill: 14, level: 81, label: "Red sandstone", blurb: "The AFK money rock, and the feedstock for high-level Crafting.", wiki: "Red sandstone" },
  { skill: 14, level: 89, label: "Seren stones", blurb: "No ore, no banking — the AFK benchmark for Mining.", wiki: "Seren stone" },
  { skill: 14, level: 90, label: "Dark animica", blurb: "Top conventional ore, and the elder rune bar supply chain.", wiki: "Dark animica" },
  { skill: 14, level: 100, label: "Primal rocks", blurb: "Tier-100 ore. Feeds primal smithing.", wiki: "Primal rocks" },
  { skill: 8, level: 68, label: "Choking ivy", blurb: "The long AFK Woodcutting band, all the way to 94.", wiki: "Choking ivy" },
  { skill: 8, level: 90, label: "Elder trees", blurb: "Best log profit, and elder logs for Firemaking.", wiki: "Elder tree" },
  { skill: 8, level: 94, label: "Crystal trees", blurb: "Prifddinas woodcutting; needs Plague's End.", wiki: "Crystal tree" },
  { skill: 8, level: 100, label: "Eternal magic trees", blurb: "Tier-100 Woodcutting.", wiki: "Eternal magic tree" },
  { skill: 10, level: 66, label: "Ghostly sole", blurb: "The longest-AFK fishing spot in the game. Needs Necromancy!.", wiki: "Ghostly sole" },
  { skill: 10, level: 94, label: "Prifddinas waterfall fishing", blurb: "Over 285k XP/hr at 99 — the single biggest jump in the skill.", wiki: "Prifddinas Waterfall Fishing" },
  { skill: 10, level: 96, label: "Wobbegongs", blurb: "High XP with far less clicking than the waterfall.", wiki: "Wobbegong" },
  { skill: 21, level: 63, label: "Red chinchompas", blurb: "GP plus a Ranged training supply.", wiki: "Red chinchompa" },
  { skill: 21, level: 75, label: "Big Game Hunter", blurb: "Anachronia's set-piece Hunter content.", wiki: "Big Game Hunter" },
  { skill: 21, level: 88, label: "Charming moths", blurb: "Hunter XP that also solves the Summoning charm bottleneck.", wiki: "Charming moth" },
  { skill: 19, level: 32, label: "Ranarr weed", blurb: "The herb run becomes worth doing.", wiki: "Ranarr weed" },
  { skill: 19, level: 85, label: "Torstol", blurb: "Overload ingredient — the herb run starts funding your Herblore.", wiki: "Torstol" },
  { skill: 19, level: 94, label: "Crystal tree seeds", blurb: "Highest-value tree run in the game.", wiki: "Crystal tree" },
  { skill: 19, level: 113, label: "Carambola trees", blurb: "Last Farming unlock before 120.", wiki: "Carambola tree" },
  { skill: 25, level: 70, label: "Hall of Memories", blurb: "Divination outfit pieces and a real step up in XP.", wiki: "Hall of Memories" },
  { skill: 25, level: 85, label: "Incandescent and cursed wisps", blurb: "Top-tier energy: the safe one and the profitable one.", wiki: "Incandescent wisp" },
  { skill: 27, level: 70, label: "Stormguard Citadel", blurb: "Third Archaeology dig site.", wiki: "Stormguard Citadel" },
  { skill: 27, level: 89, label: "Senntisten dig site", blurb: "High-tier artefacts and the Zarosian relic powers.", wiki: "Senntisten" },
  { skill: 27, level: 105, label: "Orthen", blurb: "The newest dig site and the 105-120 band.", wiki: "Orthen" },
  { skill: 27, level: 120, label: "Archaeology 120", blurb: "Master cape, and every relic power slot filled.", wiki: "Archaeology" },

  // --- Artisan ------------------------------------------------------------
  { skill: 13, level: 90, label: "Elder rune burial armour", blurb: "The Smithing workhorse from 90 to the cap.", wiki: "Elder rune bar" },
  { skill: 13, level: 99, label: "Masterwork armour", blurb: "The only Smithing that makes money rather than costing it.", wiki: "Masterwork armour" },
  { skill: 13, level: 100, label: "Primal smithing", blurb: "Tier-100 bars and armour.", wiki: "Primal bar" },
  { skill: 15, level: 82, label: "Aggression potions", blurb: "Fast Herblore XP that also sells.", wiki: "Aggression potion" },
  { skill: 15, level: 96, label: "Overloads", blurb: "The potion every combat setup is built around.", wiki: "Overload" },
  { skill: 15, level: 106, label: "Elder overload potions", blurb: "Endgame combat boost, made rather than bought.", wiki: "Elder overload potion" },
  { skill: 15, level: 120, label: "Herblore 120", blurb: "Master cape and the full salve line.", wiki: "Elder overload salve" },
  { skill: 12, level: 89, label: "Red and crystal sandstone crafting", blurb: "Crafting that pays properly.", wiki: "Red sandstone" },
  { skill: 12, level: 100, label: "Starbloom equipment", blurb: "Opens the tier-100 Crafting band.", wiki: "Starbloom" },
  { skill: 9, level: 81, label: "Rune and dragon darts", blurb: "Fastest Fletching XP in the game, and it never stops being fastest.", wiki: "Dragon dart" },
  { skill: 9, level: 100, label: "Eternal magic bows and primal crossbows", blurb: "Tier-100 Fletching.", wiki: "Eternal magic bow" },
  { skill: 11, level: 90, label: "Elder log bonfires", blurb: "Top Firemaking rate, straight through to 110.", wiki: "Elder logs" },
  { skill: 7, level: 80, label: "Cooking sharks", blurb: "AFK money and the standard Cooking method.", wiki: "Shark" },
  { skill: 7, level: 94, label: "Cavefish", blurb: "Often cheaper per XP than sharks at the same speed.", wiki: "Cavefish" },
  { skill: 20, level: 66, label: "Runespan top platform", blurb: "Fastest Runecrafting XP from here to the cap.", wiki: "Runespan" },
  { skill: 20, level: 77, label: "Nature runes via the Abyss", blurb: "Needs Enter the Abyss (miniquest).", wiki: "Abyss" },
  { skill: 20, level: 90, label: "Soul runes", blurb: "The best Runecrafting money in the game.", wiki: "Soul altar" },

  // --- Support ------------------------------------------------------------
  { skill: 16, level: 52, label: "Wilderness Agility Course", blurb: "The long middle of the Agility skill.", wiki: "Wilderness Agility Course" },
  { skill: 16, level: 85, label: "Island-wide Anachronia course", blurb: "Best Agility XP to 99.", wiki: "Anachronia Agility Course" },
  { skill: 17, level: 62, label: "Safecracking", blurb: "The modern spine of Thieving, from 62 to 95.", wiki: "Safecracking" },
  { skill: 17, level: 95, label: "Vault of Hereditas", blurb: "Heists open — the 95-120 Thieving content.", wiki: "Vault of Hereditas" },
  { skill: 17, level: 108, label: "Asuran Arsenal", blurb: "Top heist, top Thieving rate.", wiki: "Asuran Arsenal" },
  { skill: 22, level: 75, label: "Gilded altar", blurb: "Your own Prayer altar — the single most useful room in a house.", wiki: "Gilded altar" },
  { skill: 22, level: 80, label: "Potion cauldrons", blurb: "Fastest Construction XP, added in the 2026 update.", wiki: "Potion cauldron" },
  { skill: 23, level: 96, label: "Pack yak", blurb: "Top-tier beast of burden. Note: 96, not 67.", wiki: "Pack yak pouch" },
  { skill: 23, level: 99, label: "Iron titan", blurb: "Best combat familiar, and the Summoning cape.", wiki: "Iron titan pouch" },
  { skill: 24, level: 35, label: "Sinkholes", blurb: "Daily Dungeoneering burst — a few minutes for a large chunk of XP.", wiki: "Sinkhole" },
  { skill: 24, level: 90, label: "Elite Dungeons", blurb: "Better hours than floors once you count the combat XP and drops.", wiki: "Elite Dungeons" },
  { skill: 24, level: 120, label: "Dungeoneering 120", blurb: "Master cape and every Daemonheim reward unlocked.", wiki: "Daemonheim" },
  { skill: 26, level: 80, label: "Ancient Invention", blurb: "Needs Desperate Times. Ancient gizmos and the perks worth having.", wiki: "Ancient Invention" },
  { skill: 26, level: 86, label: "Gizmo creation", blurb: "Direct Invention XP when you want levels now.", wiki: "Invention" },
  { skill: 26, level: 120, label: "Invention 120", blurb: "Not the cap — Invention runs to 150, and 120 is only the halfway marker.", wiki: "Invention" },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Methods usable at `level`, best XP first.
 *
 * A method with a `maxLevel` drops out once you pass it — not because it stops
 * working, but because it has stopped being the right way to spend the hour,
 * which is the question this list answers.
 */
export function methodsFor(skill: number, level: number): TrainingMethod[] {
  const all = TRAINING[skill] ?? [];
  return all
    .filter((m) => level >= m.minLevel && (m.maxLevel === undefined || level <= m.maxLevel))
    .sort((a, b) => b.xpPerHour - a.xpPerHour);
}

/** The next meaningful threshold above `level`, or null if none remain. */
export function nextUnlock(skill: number, level: number): SkillUnlock | null {
  let best: SkillUnlock | null = null;
  for (const u of UNLOCKS) {
    if (u.skill !== skill || u.level <= level) continue;
    if (best === null || u.level < best.level) best = u;
  }
  return best;
}

/**
 * Hours of grinding between two XP values at a given rate.
 *
 * Returns Infinity for a rate of zero rather than dividing — some entries
 * (charm gathering, the XP capacitor) genuinely have no hourly rate, and a
 * silent NaN would poison every total downstream.
 */
export function timeToLevel(currentXp: number, targetXp: number, xpPerHour: number): number {
  const remaining = targetXp - currentXp;
  if (remaining <= 0) return 0;
  if (xpPerHour <= 0) return Infinity;
  return remaining / xpPerHour;
}
