import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1440,height:900} });
await p.goto('http://localhost:4173/rs3-leaderboard/quests/', { waitUntil:'networkidle' });
await p.waitForTimeout(600);
await p.screenshot({ path:'.review/shots/a11y/quests-top.png' });
await p.evaluate(`window.scrollTo(0,1200)`); await p.waitForTimeout(300);
await p.screenshot({ path:'.review/shots/a11y/quests-rows.png' });
await p.goto('http://localhost:4173/rs3-leaderboard/money/', { waitUntil:'networkidle' });
await p.waitForTimeout(600);
await p.screenshot({ path:'.review/shots/a11y/money-top.png' });
await p.goto('http://localhost:4173/rs3-leaderboard/pvm/', { waitUntil:'networkidle' });
await p.waitForTimeout(600);
await p.screenshot({ path:'.review/shots/a11y/pvm-top.png' });
await b.close();
