import { chromium } from '@playwright/test';
const BASE = 'http://localhost:4173/rs3-leaderboard';
const OUT = '/home/mbaraofiorin/dev/rs3-leaderboard/.review/shots/interaction';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
const log = (...a) => console.log(...a);
await p.goto(BASE + '/goals/', { waitUntil: 'networkidle' });
await p.waitForTimeout(1600);
const tiles = () => p.locator('main div.grid').first().innerText();
const overall = () => p.locator('text=/% overall/').first().innerText();
const pill = () => p.locator('text=/\\d+ \\/ \\d+ done/i').first().innerText();
const tierPcts = () => p.locator('main section h3 span.text-ink-faint').allInnerTexts();
log('DECXUS: tiles =', (await tiles()).replace(/\n/g,' '), '| overall =', await overall(), '| pill =', await pill());
log('  section tier % =', (await tierPcts()).join(','));
await p.locator('[role=group][aria-label=Player] button').nth(1).click();
await p.waitForTimeout(900);
log('SOCLOPATA: tiles =', (await tiles()).replace(/\n/g,' '), '| overall =', await overall(), '| pill =', await pill());
log('  section tier % =', (await tierPcts()).join(','));
await p.screenshot({ path: OUT + '/x-goals-ribbon-soclo.png' });
await b.close();
