import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1440,height:900} });
await p.goto('http://localhost:4173/rs3-leaderboard/skills',{waitUntil:'networkidle'});
await p.waitForTimeout(1200);
const names = async () => p.evaluate(()=>[...document.querySelectorAll('button')].map(b=>b.innerText.replace(/\n/g,' ').trim()).filter(t=>/\/\d+/.test(t)).map(t=>t.split(' ')[0]));
const state = async () => p.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>['ALL','COMBAT','GATHER','ARTISAN','SUPPORT','ORDER','GAP','XP','A-Z'].includes(b.innerText.trim())).map(b=>b.innerText.trim()+':'+(b.getAttribute('aria-pressed')??b.getAttribute('aria-current')??'?')));
console.log('initial', (await names()).length, JSON.stringify(await state()));
await p.getByRole('button',{name:'COMBAT',exact:true}).click();
await p.waitForTimeout(600);
console.log('after COMBAT', JSON.stringify(await names()), JSON.stringify(await state()));
await p.getByRole('button',{name:'GAP',exact:true}).click();
await p.waitForTimeout(600);
console.log('after GAP', JSON.stringify(await names()));
await p.getByRole('button',{name:'A-Z',exact:true}).click();
await p.waitForTimeout(600);
console.log('after A-Z', JSON.stringify(await names()));
await p.getByRole('button',{name:'GATHER',exact:true}).click();
await p.waitForTimeout(600);
console.log('after GATHER', JSON.stringify(await names()));
await p.screenshot({path:'.review/shots/desktop-core/skills-gather.png',fullPage:true});
await b.close();
