import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1440,height:900} });
await p.goto('http://localhost:4173/rs3-leaderboard/skills',{waitUntil:'networkidle'});
await p.waitForTimeout(1200);
const raw = await p.evaluate(()=>[...document.querySelectorAll('button')].slice(0,14).map(b=>({txt:b.textContent, aria:b.getAttribute('aria-pressed'), cur:b.getAttribute('aria-current'), cls:b.className.slice(0,60)})));
console.log(JSON.stringify(raw,null,1));
const names = async () => p.evaluate(()=>[...document.querySelectorAll('button')].map(b=>b.textContent.trim()).filter(t=>/\/\d+/.test(t)));
const clickTxt = async (t) => p.evaluate((t)=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim().toLowerCase()===t.toLowerCase()); if(!b) throw new Error('no '+t); b.click(); return true;}, t);
console.log('initial n=', (await names()).length);
await clickTxt('combat'); await p.waitForTimeout(600);
console.log('after combat', JSON.stringify(await names()));
await clickTxt('gap'); await p.waitForTimeout(600);
console.log('after gap', JSON.stringify(await names()));
await clickTxt('all'); await clickTxt('a-z'); await p.waitForTimeout(600);
console.log('after all+az', JSON.stringify((await names()).slice(0,6)));
await b.close();
