import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1440,height:900} });
await p.goto('http://localhost:4173/rs3-leaderboard/skills/', { waitUntil:'networkidle' });
await p.waitForTimeout(500);
const st = () => p.evaluate(`(()=>{const g=document.querySelector('[role="tablist"]');const tabs=[...g.querySelectorAll('[role="tab"]')];return{selected:tabs.find(t=>t.getAttribute('aria-selected')==='true').innerText,active:document.activeElement.innerText.trim(),tabIndexes:tabs.map(t=>t.getAttribute('tabindex')),ariaControls:tabs.map(t=>t.getAttribute('aria-controls')),panels:document.querySelectorAll('[role="tabpanel"]').length};})()`);
await p.locator('[role="tablist"] [role="tab"]').first().focus();
console.log('focused first tab:', await st());
await p.keyboard.press('ArrowRight'); await p.waitForTimeout(300);
console.log('after ArrowRight:', await st());
await p.keyboard.press('Tab'); await p.waitForTimeout(200);
console.log('after Tab (should skip to next widget in tablist pattern):', await st());
await b.close();
